// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using one_to_many;

namespace one_to_many.Migrations
{
    [DbContext(typeof(ClassRoom))]
    partial class ClassRoomModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .UseIdentityColumns()
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.2");

            modelBuilder.Entity("one_to_many.Grade", b =>
                {
                    b.Property<int>("gradeid")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<string>("grade_name")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("gradeid");

                    b.ToTable("Grades");
                });

            modelBuilder.Entity("one_to_many.Student", b =>
                {
                    b.Property<int>("studentid")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<int>("gradeid")
                        .HasColumnType("int");

                    b.Property<int>("student_age")
                        .HasColumnType("int");

                    b.Property<string>("student_name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<long>("student_phone")
                        .HasColumnType("bigint");

                    b.HasKey("studentid");

                    b.HasIndex("gradeid");

                    b.ToTable("Students");
                });

            modelBuilder.Entity("one_to_many.Student", b =>
                {
                    b.HasOne("one_to_many.Grade", "grade")
                        .WithMany()
                        .HasForeignKey("gradeid")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("grade");
                });
#pragma warning restore 612, 618
        }
    }
}
